#!/usr/bin/env node
// =============================================================================
// Generate beautiful HTML report from scraped Instagram data
// Reads raw-posts.json + transcripts + hook screenshots + report-analysis.json
//
// report-analysis.json is generated by Claude Code analyzing the scraped data.
// It contains hand-written style visual hook descriptions, spoken hook analysis,
// and "why it worked" insights for each top post, plus winning patterns.
// If report-analysis.json is missing, falls back to programmatic analysis.
//
// Usage: node scripts/report-html.js <project-name>
// =============================================================================

import { readFileSync, writeFileSync, existsSync, readdirSync } from 'fs';
import { join } from 'path';

const projectName = process.argv[2];
if (!projectName) {
  console.error('Usage: node scripts/report-html.js <project-name>');
  process.exit(1);
}

const projectDir = join(import.meta.dirname, '..', 'projects', projectName);
const rawPostsFile = join(projectDir, 'raw-posts.json');
const analysisFile = join(projectDir, 'report-analysis.json');
const transcriptsDir = join(projectDir, 'transcripts');
const hooksDir = join(projectDir, 'hook-screenshots');
const outputFile = join(projectDir, 'report.html');

if (!existsSync(rawPostsFile)) {
  console.error('No raw-posts.json found. Run scrape.js first.');
  process.exit(1);
}

const data = JSON.parse(readFileSync(rawPostsFile, 'utf8'));
const config = existsSync(join(projectDir, 'config.json'))
  ? JSON.parse(readFileSync(join(projectDir, 'config.json'), 'utf8'))
  : {};

// =============================================================================
// Data processing
// =============================================================================

// Parse a number string that may be English (1,234 / 8.6K) or French (1 234 / 8,6 K)
function parseFrenchEnglishNumber(str) {
  if (!str) return 0;
  const match = str.match(/([\d]+(?:[.,\s ]\d+)*)\s*([KkMm])?/);
  if (!match) return 0;
  let numStr = match[1].replace(/[\s ]/g, ''); // strip spaces and non-breaking spaces
  // French decimal: single comma followed by 1-2 digits at end (e.g. "8,6")
  if (/^\d+,\d{1,2}$/.test(numStr)) {
    numStr = numStr.replace(',', '.');
  } else {
    // English thousands: commas followed by 3 digits (e.g. "1,234")
    numStr = numStr.replace(/,/g, '');
  }
  let num = parseFloat(numStr);
  if (isNaN(num)) return 0;
  if (match[2]?.match(/[Kk]/)) num *= 1000;
  if (match[2]?.match(/[Mm]/)) num *= 1000000;
  return num;
}

function parseEngagement(post) {
  const likeStr = post.likes || post.likesFromBtn || '';
  const contextStr = post.likesContext || '';
  const viewStr = post.views || '';

  let num = parseFrenchEnglishNumber(likeStr);
  if (num > 0) return num;

  const ctxMatch = contextStr.match(/(?:and|et)\s+([\d,.\s ]+)\s*([KkMm])?\s*others/i);
  if (ctxMatch) {
    let ctxStr = ctxMatch[1].replace(/[\s ]/g, '');
    if (/^\d+,\d{1,2}$/.test(ctxStr)) {
      ctxStr = ctxStr.replace(',', '.');
    } else {
      ctxStr = ctxStr.replace(/,/g, '');
    }
    let ctxNum = parseFloat(ctxStr);
    if (!isNaN(ctxNum)) {
      if (ctxMatch[2]?.match(/[Kk]/)) ctxNum *= 1000;
      if (ctxMatch[2]?.match(/[Mm]/)) ctxNum *= 1000000;
      return ctxNum + 1;
    }
  }

  num = parseFrenchEnglishNumber(viewStr);
  if (num > 0) return num;

  return 0;
}

function formatNumber(num) {
  if (num >= 1000000) return (num / 1000000).toFixed(1).replace(/\.0$/, '') + 'M';
  if (num >= 1000) return (num / 1000).toFixed(1).replace(/\.0$/, '') + 'K';
  return num.toLocaleString();
}

function getPostId(post) {
  return (post.href || post.url || '').match(/\/(p|reel)\/([\w-]+)/)?.[2] || '';
}

function loadTranscript(postId) {
  const txtFile = join(transcriptsDir, `${postId}.txt`);
  if (existsSync(txtFile)) return readFileSync(txtFile, 'utf8').trim();
  return null;
}

function hasScreenshots(postId) {
  return existsSync(join(hooksDir, `${postId}_0s.jpg`));
}

function extractFirstLine(text) {
  if (!text) return '';
  return text.split('\n').find(l => l.trim().length > 5)?.trim() || text.substring(0, 100);
}

// Process all posts
const posts = data.posts.map(p => ({
  ...p,
  engagementNum: parseEngagement(p),
  postId: getPostId(p),
  transcript: loadTranscript(getPostId(p)),
  hasScreenshots: hasScreenshots(getPostId(p)),
})).sort((a, b) => b.engagementNum - a.engagementNum);

const reels = posts.filter(p => p.type === 'reel');
const images = posts.filter(p => p.type === 'image');
const withTranscripts = posts.filter(p => p.transcript);
const top6 = posts.slice(0, 6);
const topLikes = top6[0] ? formatNumber(top6[0].engagementNum) : '0';

// Load Claude Code analysis if available
let analysis = null;
if (existsSync(analysisFile)) {
  analysis = JSON.parse(readFileSync(analysisFile, 'utf8'));
  console.log('  Using Claude Code analysis (report-analysis.json)');
} else {
  console.log('  No report-analysis.json found, using programmatic analysis');
}

function getAnalysisForPost(postId) {
  if (!analysis || !analysis.posts) return null;
  return analysis.posts.find(p => p.postId === postId) || null;
}

// =============================================================================
// Pattern analysis
// =============================================================================

function analyzePatterns() {
  const patterns = [];
  const totalPosts = posts.length;

  // 1. Format breakdown
  const reelPct = Math.round(reels.length / totalPosts * 100);
  const imagePct = 100 - reelPct;
  if (reelPct >= 80) {
    patterns.push({
      title: `${reelPct}% of Top Content is Reels`,
      desc: `Out of ${totalPosts} posts analyzed, ${reels.length} are Reels and only ${images.length} are images or carousels. ${reelPct >= 90 ? 'Carousels are a massive pattern interrupt opportunity in this niche since almost nobody is using them.' : 'Reels dominate this niche, but the low carousel supply means they could stand out.'}`
    });
  } else if (imagePct >= 40) {
    patterns.push({
      title: `Mixed Format Niche: ${reelPct}% Reels, ${imagePct}% Images`,
      desc: `This niche uses both Reels and image/carousel posts. Both formats can perform well here. Test which resonates with your specific audience.`
    });
  } else {
    patterns.push({
      title: `Reels Dominate at ${reelPct}%`,
      desc: `Reels are the primary format in this niche with ${reels.length} out of ${totalPosts} posts. Consider how to differentiate within the Reels format or use carousels as a pattern interrupt.`
    });
  }

  // 2. Comment CTA pattern
  const commentCTAs = posts.filter(p => {
    const caption = (p.caption || p.fullCaption || '').toLowerCase();
    const transcript = (p.transcript || '').toLowerCase();
    return /comment\s+['""]?\w+['""]?/i.test(caption) || /comment\s+\w+/i.test(transcript);
  });
  if (commentCTAs.length >= 2) {
    const ctaPct = Math.round(commentCTAs.length / totalPosts * 100);
    patterns.push({
      title: '"Comment [WORD]" CTAs Drive Engagement',
      desc: `${commentCTAs.length} posts (${ctaPct}%) use comment-bait CTAs like "Comment PROMPT" or "Comment STRATEGY". This pattern turns viewers into commenters and triggers the algorithm to push the post further.`
    });
  }

  // 3. Hook analysis — specific numbers/dollar amounts
  const numberHooks = top6.filter(p => {
    const hook = p.transcript ? extractFirstLine(p.transcript) : (p.caption || '').substring(0, 100);
    return /\$[\d,.]+|\d+[KkMm]\b|\d{2,}/.test(hook);
  });
  if (numberHooks.length >= 2) {
    patterns.push({
      title: 'Specific Numbers Stop the Scroll',
      desc: `${numberHooks.length} of the top 6 posts open with specific numbers or dollar amounts in the hook. Specificity creates instant credibility and curiosity. Vague claims get scrolled past.`
    });
  }

  // 4. Hook length — short vs long
  const shortHooks = top6.filter(p => {
    const hook = p.transcript ? extractFirstLine(p.transcript) : '';
    return hook.length > 0 && hook.split(' ').length <= 12;
  });
  if (shortHooks.length >= 3) {
    patterns.push({
      title: 'Short Hooks Win',
      desc: `${shortHooks.length} of the top 6 posts use hooks under 12 words. The best-performing hooks in this niche are punchy and direct. They create a curiosity gap in one sentence, not a paragraph.`
    });
  }

  // 5. Content themes from captions
  const frameworkPosts = posts.filter(p => {
    const text = ((p.caption || '') + ' ' + (p.transcript || '')).toLowerCase();
    return /step\s*\d|method|framework|system|strategy|formula/i.test(text);
  });
  if (frameworkPosts.length >= 3) {
    const fPct = Math.round(frameworkPosts.length / totalPosts * 100);
    patterns.push({
      title: 'Frameworks and Systems Perform Best',
      desc: `${frameworkPosts.length} posts (${fPct}%) teach a named method, step-by-step system, or framework. Giving your approach a name makes it memorable, saveable, and positions you as the authority who created it.`
    });
  }

  // 6. Talking head / raw format
  if (reelPct >= 70) {
    const talkingHead = reels.filter(p => {
      const text = ((p.caption || '') + ' ' + (p.transcript || '')).toLowerCase();
      return p.transcript && p.transcript.length > 100;
    });
    if (talkingHead.length >= Math.floor(reels.length * 0.5)) {
      patterns.push({
        title: 'Raw Talking Head Format Dominates',
        desc: `Most top Reels in this niche are simple talking-head videos with text overlay. No complex editing, no B-roll. The creator talking directly to camera builds trust and feels personal, like a FaceTime call.`
      });
    }
  }

  // Ensure we have at least 3 patterns, pad with generic insights if needed
  if (patterns.length < 3) {
    if (!patterns.find(p => p.title.includes('Transcript'))) {
      patterns.push({
        title: 'Spoken Hooks Matter More Than Visuals',
        desc: `With ${withTranscripts.length} transcribed videos, the data shows that what creators SAY in the first 3 seconds matters more than how the video looks. The top hooks are conversational and direct, not polished or scripted.`
      });
    }
  }

  return patterns.slice(0, 6); // Max 6 patterns
}

const patterns = (analysis && analysis.winningPatterns) ? analysis.winningPatterns : analyzePatterns();

// =============================================================================
// Generate HTML
// =============================================================================

function escapeHtml(text) {
  return (text || '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

// Analyze why a post worked based on its data
function analyzeWhyItWorked(post) {
  const reasons = [];
  const caption = (post.caption || post.fullCaption || '').toLowerCase();
  const transcript = (post.transcript || '').toLowerCase();
  const hook = post.transcript ? extractFirstLine(post.transcript) : '';
  const allText = caption + ' ' + transcript;

  // Comment CTA
  if (/comment\s+['""]?\w+['""]?/i.test(allText)) {
    const match = allText.match(/comment\s+['""]?(\w+)['""]?/i);
    const keyword = match ? match[1].toUpperCase() : 'KEYWORD';
    reasons.push(`Comment-bait CTA ("Comment ${keyword}") drives massive comment volume and triggers algorithmic distribution.`);
  }

  // Specific numbers in hook
  if (/\$[\d,.]+|\d+[KkMm]\b|\d{3,}/.test(hook)) {
    reasons.push('Specific numbers in the opening hook create instant credibility and curiosity. Vague claims get scrolled past.');
  }

  // Named framework or method
  if (/method|framework|system|formula|strategy|step\s*\d/i.test(allText)) {
    reasons.push('Named framework or step-by-step system is memorable, saveable, and positions the creator as an authority.');
  }

  // Short punchy hook
  if (hook && hook.split(' ').length <= 10) {
    reasons.push('Ultra-short hook (under 10 words) creates an immediate curiosity gap that demands the viewer keep watching.');
  }

  // Question format
  if (hook && hook.includes('?')) {
    reasons.push('Opening with a question triggers the viewer to mentally answer it, increasing watch time and engagement.');
  }

  // High engagement
  if (post.engagementNum >= 10000) {
    reasons.push(`${formatNumber(post.engagementNum)}+ engagement signals strong resonance with this niche audience. The algorithm rewards this with exponentially more distribution.`);
  }

  // Comparison/versus format
  if (/vs\.?|versus|compared|before.*after|slow.*fast/i.test(allText)) {
    reasons.push('Comparison format (X vs Y) is one of the highest-performing formats in this niche. Easy to understand, easy to save, easy to share.');
  }

  // Promise with timeframe
  if (/\d+\s*(minutes?|mins?|seconds?|secs?|hours?|days?|weeks?)/i.test(hook)) {
    reasons.push('Specific time promise in the hook sets clear expectations and makes the value feel achievable and immediate.');
  }

  // Fallback if no patterns detected
  if (reasons.length === 0) {
    reasons.push('Strong execution of format and topic that resonated with this niche audience.');
  }

  return reasons.slice(0, 3); // Max 3 reasons per post
}

// Describe the visual hook from screenshots context
function describeVisualHook(post) {
  const caption = (post.caption || '').toLowerCase();
  const transcript = (post.transcript || '').toLowerCase();

  // Try to infer visual description from content clues
  if (/split screen|side by side|comparison|vs/i.test(caption + ' ' + transcript)) {
    return 'Split-screen or comparison visual format with text overlay';
  }
  if (/whiteboard|board|writing|draw/i.test(caption + ' ' + transcript)) {
    return 'Whiteboard or hand-drawn visual teaching format';
  }
  if (/screen recording|screencast|demo/i.test(caption + ' ' + transcript)) {
    return 'Screen recording or live demo walkthrough';
  }
  if (/pointing|text on screen|overlay/i.test(caption + ' ' + transcript)) {
    return 'Creator with text overlay or floating graphics on screen';
  }
  if (post.type === 'reel') {
    return 'Talking head with text overlay (see screenshots for first 3 seconds)';
  }
  return 'See screenshots below for visual hook analysis';
}

function generatePostCard(post, rank) {
  const engNum = post.engagementNum;
  const likes = post.likes || formatNumber(engNum);
  const comments = post.comments || post.commentsCount || '';
  const author = post.author || 'unknown';
  const postType = (post.type || 'reel').toUpperCase();
  const postId = post.postId;
  const transcript = post.transcript;
  const spokenHook = transcript ? extractFirstLine(transcript) : '';
  const captionPreview = (post.caption || '').substring(0, 200);
  const url = post.url || ('https://www.instagram.com' + post.href);
  const postAnalysis = getAnalysisForPost(postId);
  const visualHookDesc = postAnalysis?.visualHook || describeVisualHook(post);
  const spokenHookDesc = postAnalysis?.spokenHook || null;
  const whyItWorked = postAnalysis?.whyItWorked || analyzeWhyItWorked(post).join(' ');

  let screenshotsHtml = '';
  if (post.hasScreenshots) {
    screenshotsHtml = `
        <div class="screenshots">
          <div>
            <img src="hook-screenshots/${postId}_0s.jpg" alt="0s">
            <div class="ss-label">0 seconds</div>
          </div>
          <div>
            <img src="hook-screenshots/${postId}_1s.jpg" alt="1s">
            <div class="ss-label">1 second</div>
          </div>
          <div>
            <img src="hook-screenshots/${postId}_2s.jpg" alt="2s">
            <div class="ss-label">2 seconds</div>
          </div>
        </div>`;
  }

  // Visual hook section
  let visualHookHtml = `
        <div class="hook-section">
          <div class="hook-label">Visual Hook</div>
          <div class="hook-text">${escapeHtml(visualHookDesc)}</div>
        </div>`;

  // Spoken hook section
  let spokenHookHtml = '';
  const spokenHookDisplay = spokenHookDesc || (spokenHook ? `"${spokenHook}"` : '');
  if (spokenHookDisplay) {
    spokenHookHtml = `
        <div class="hook-section">
          <div class="hook-label">Spoken Hook</div>
          <div class="hook-text">${escapeHtml(spokenHookDisplay)}</div>
        </div>`;
  }

  // Full transcript
  let transcriptHtml = '';
  if (transcript) {
    transcriptHtml = `
        <div class="transcript">${escapeHtml(transcript)}</div>`;
  }

  // Why it worked
  let whyHtml = `
        <div class="why-worked"><strong>Why it worked:</strong> ${escapeHtml(whyItWorked)}</div>`;

  // Caption preview
  let captionHtml = '';
  if (captionPreview && captionPreview.length > 20) {
    captionHtml = `
        <div class="caption-preview"><strong>Caption:</strong> ${escapeHtml(captionPreview)}${post.caption && post.caption.length > 200 ? '...' : ''}</div>`;
  }

  // Parse engagement display
  let engHtml = `<div class="eng-item"><strong>${escapeHtml(likes)}</strong>Likes</div>`;
  if (comments) {
    const commentsText = typeof comments === 'string' ? comments.replace(/View all /i, '').replace(/ comments?/i, '') : comments;
    engHtml += `\n          <div class="eng-item"><strong>${escapeHtml(String(commentsText))}</strong>Comments</div>`;
  }

  return `
      <div class="post-card">
        <div class="post-header">
          <div>
            <span class="post-rank">#${rank}</span>
            <span class="post-author">@${escapeHtml(author)}</span>
            <span class="post-type">${postType}</span>
          </div>
        </div>
        <div class="engagement-row">
          ${engHtml}
        </div>${screenshotsHtml}${visualHookHtml}${spokenHookHtml}${transcriptHtml}${whyHtml}${captionHtml}
      </div>`;
}

function generatePatternCard(pattern, index) {
  return `
        <div class="pattern-card">
          <div class="pattern-num">${String(index + 1).padStart(2, '0')}</div>
          <h3>${escapeHtml(pattern.title)}</h3>
          <p>${escapeHtml(pattern.desc)}</p>
        </div>`;
}

const nicheTitle = config.niche || projectName.replace(/-/g, ' ');
const niceDate = new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' });
const searchTerms = (config.searchTerms || []).map(t => '#' + t).join(', ') || 'N/A';

const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Instagram Research Report | ${escapeHtml(nicheTitle)}</title>
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&display=swap');

    * { margin: 0; padding: 0; box-sizing: border-box; }

    body {
      font-family: 'Inter', -apple-system, sans-serif;
      background: #0A0A08;
      color: #F5F0E8;
      line-height: 1.7;
    }

    .container { max-width: 1100px; margin: 0 auto; padding: 0 40px; }

    .hero {
      padding: 80px 0 60px;
      border-bottom: 1px solid rgba(212, 168, 67, 0.15);
    }
    .hero-label {
      text-transform: uppercase;
      letter-spacing: 4px;
      font-size: 11px;
      color: #D4A843;
      font-weight: 600;
      margin-bottom: 16px;
    }
    .hero h1 {
      font-size: 48px;
      font-weight: 800;
      line-height: 1.1;
      color: #FFFFFF;
      margin-bottom: 16px;
    }
    .hero h1 span { color: #D4A843; }
    .hero .subtitle {
      font-size: 18px;
      color: rgba(245, 240, 232, 0.5);
      max-width: 600px;
    }
    .hero-meta {
      display: flex;
      gap: 32px;
      margin-top: 32px;
      flex-wrap: wrap;
    }
    .hero-meta-item {
      font-size: 13px;
      color: rgba(245, 240, 232, 0.35);
    }
    .hero-meta-item strong {
      color: rgba(245, 240, 232, 0.6);
    }

    .stats-bar {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));
      gap: 1px;
      background: rgba(212, 168, 67, 0.1);
      border-radius: 12px;
      overflow: hidden;
      margin: 48px 0;
    }
    .stat-card {
      background: rgba(245, 240, 232, 0.03);
      padding: 28px 24px;
      text-align: center;
    }
    .stat-card .number {
      font-size: 36px;
      font-weight: 800;
      color: #D4A843;
      line-height: 1;
    }
    .stat-card .label {
      font-size: 12px;
      text-transform: uppercase;
      letter-spacing: 2px;
      color: rgba(245, 240, 232, 0.4);
      margin-top: 8px;
    }

    .section {
      padding: 60px 0;
      border-bottom: 1px solid rgba(245, 240, 232, 0.06);
    }
    .section-label {
      text-transform: uppercase;
      letter-spacing: 3px;
      font-size: 11px;
      color: #D4A843;
      font-weight: 600;
      margin-bottom: 12px;
    }
    .section h2 {
      font-size: 32px;
      font-weight: 700;
      color: #FFFFFF;
      margin-bottom: 8px;
    }
    .section .section-desc {
      font-size: 15px;
      color: rgba(245, 240, 232, 0.4);
      margin-bottom: 40px;
      max-width: 600px;
    }

    .post-card {
      background: rgba(245, 240, 232, 0.03);
      border: 1px solid rgba(245, 240, 232, 0.06);
      border-radius: 16px;
      padding: 32px;
      margin-bottom: 24px;
      transition: border-color 0.2s;
    }
    .post-card:hover {
      border-color: rgba(212, 168, 67, 0.3);
    }
    .post-header {
      display: flex;
      justify-content: space-between;
      align-items: flex-start;
      margin-bottom: 20px;
      flex-wrap: wrap;
      gap: 12px;
    }
    .post-rank {
      font-size: 14px;
      font-weight: 700;
      color: #D4A843;
      background: rgba(212, 168, 67, 0.1);
      padding: 4px 12px;
      border-radius: 6px;
    }
    .post-author {
      font-size: 16px;
      font-weight: 600;
      color: #FFFFFF;
    }
    .post-type {
      font-size: 11px;
      text-transform: uppercase;
      letter-spacing: 1px;
      padding: 3px 10px;
      border-radius: 4px;
      background: rgba(212, 168, 67, 0.15);
      color: #D4A843;
      font-weight: 600;
    }

    .engagement-row {
      display: flex;
      gap: 24px;
      margin-bottom: 20px;
      flex-wrap: wrap;
    }
    .eng-item {
      font-size: 13px;
      color: rgba(245, 240, 232, 0.5);
    }
    .eng-item strong {
      font-size: 20px;
      font-weight: 700;
      color: #FFFFFF;
      display: block;
      margin-bottom: 2px;
    }

    .screenshots {
      display: grid;
      grid-template-columns: repeat(3, 1fr);
      gap: 8px;
      margin: 20px 0;
      border-radius: 12px;
      overflow: hidden;
    }
    .screenshots img {
      width: 100%;
      height: auto;
      display: block;
    }
    .ss-label {
      font-size: 10px;
      text-transform: uppercase;
      letter-spacing: 1px;
      color: rgba(245, 240, 232, 0.25);
      text-align: center;
      padding: 4px 0;
      background: rgba(245, 240, 232, 0.03);
    }

    .hook-section { margin: 16px 0; }
    .hook-label {
      font-size: 11px;
      text-transform: uppercase;
      letter-spacing: 2px;
      color: #D4A843;
      font-weight: 600;
      margin-bottom: 6px;
    }
    .hook-text {
      font-size: 18px;
      font-weight: 600;
      color: #FFFFFF;
      font-style: italic;
      padding-left: 16px;
      border-left: 3px solid #D4A843;
    }

    .transcript {
      background: rgba(245, 240, 232, 0.02);
      border: 1px solid rgba(245, 240, 232, 0.05);
      border-radius: 8px;
      padding: 16px 20px;
      margin: 12px 0;
      font-size: 13px;
      color: rgba(245, 240, 232, 0.5);
      line-height: 1.8;
      max-height: 200px;
      overflow-y: auto;
    }
    .transcript::-webkit-scrollbar { width: 4px; }
    .transcript::-webkit-scrollbar-thumb { background: rgba(212, 168, 67, 0.3); border-radius: 2px; }

    .why-worked {
      margin-top: 16px;
      padding: 16px 20px;
      background: rgba(212, 168, 67, 0.05);
      border-left: 3px solid rgba(212, 168, 67, 0.3);
      border-radius: 0 8px 8px 0;
      font-size: 14px;
      color: rgba(245, 240, 232, 0.6);
      line-height: 1.7;
    }
    .why-worked strong {
      color: #D4A843;
    }

    .caption-preview {
      font-size: 13px;
      color: rgba(245, 240, 232, 0.4);
      margin-top: 12px;
      padding-top: 12px;
      border-top: 1px solid rgba(245, 240, 232, 0.05);
    }
    .caption-preview strong { color: rgba(245, 240, 232, 0.6); }

    .pattern-grid {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
      gap: 16px;
    }
    .pattern-card {
      background: rgba(245, 240, 232, 0.03);
      border: 1px solid rgba(245, 240, 232, 0.06);
      border-radius: 12px;
      padding: 28px;
    }
    .pattern-card .pattern-num {
      font-size: 32px;
      font-weight: 800;
      color: #D4A843;
      line-height: 1;
      margin-bottom: 12px;
    }
    .pattern-card h3 {
      font-size: 16px;
      font-weight: 600;
      color: #FFFFFF;
      margin-bottom: 8px;
    }
    .pattern-card p {
      font-size: 14px;
      color: rgba(245, 240, 232, 0.5);
    }

    .footer {
      padding: 48px 0;
      text-align: center;
      font-size: 13px;
      color: rgba(245, 240, 232, 0.2);
    }
    .footer a {
      color: #D4A843;
      text-decoration: none;
      font-weight: 600;
    }
    .footer a:hover { text-decoration: underline; }
  </style>
</head>
<body>

  <div class="container">

    <div class="hero">
      <div class="hero-label">Instagram Research Report</div>
      <h1>${escapeHtml(nicheTitle.split(' ').slice(0, 3).join(' '))} <span>${escapeHtml(nicheTitle.split(' ').slice(3).join(' ') || 'Niche Analysis')}</span></h1>
      <p class="subtitle">Top-performing posts analyzed with visual hooks, spoken hooks, transcripts, and engagement patterns.</p>
      <div class="hero-meta">
        <div class="hero-meta-item"><strong>Project:</strong> ${escapeHtml(config.name || projectName)}</div>
        <div class="hero-meta-item"><strong>Niche:</strong> ${escapeHtml(config.niche || projectName)}</div>
        <div class="hero-meta-item"><strong>Search:</strong> ${escapeHtml(searchTerms)}</div>
        <div class="hero-meta-item"><strong>Date:</strong> ${niceDate}</div>
      </div>
    </div>

    <div class="stats-bar">
      <div class="stat-card">
        <div class="number">${posts.length}</div>
        <div class="label">Posts Analyzed</div>
      </div>
      <div class="stat-card">
        <div class="number">${Math.round(reels.length / posts.length * 100)}%</div>
        <div class="label">Reels</div>
      </div>
      <div class="stat-card">
        <div class="number">${withTranscripts.length}</div>
        <div class="label">Transcribed</div>
      </div>
      <div class="stat-card">
        <div class="number">${posts.filter(p => p.hasScreenshots).length}</div>
        <div class="label">Visual Hooks</div>
      </div>
      <div class="stat-card">
        <div class="number">${topLikes}</div>
        <div class="label">Top Likes</div>
      </div>
    </div>

    <div class="section">
      <div class="section-label">Top Performers</div>
      <h2>Highest Engagement Posts</h2>
      <p class="section-desc">The top ${top6.length} posts by engagement, with full visual + spoken hook analysis and transcripts.</p>

${top6.map((p, i) => generatePostCard(p, i + 1)).join('\n')}
    </div>

    <div class="section">
      <div class="section-label">Key Insights</div>
      <h2>Winning Patterns</h2>
      <p class="section-desc">Patterns extracted from the top-performing content in this niche. Use these to inform your content strategy.</p>

      <div class="pattern-grid">
${patterns.map((p, i) => generatePatternCard(p, i)).join('\n')}
      </div>
    </div>

    <div class="footer">
      <p>Built by <a href="https://www.instagram.com/leifabel11" target="_blank">Leif Abel</a> | IG Research Tool</p>
      <p style="margin-top: 8px;">Leif Abel &copy; ${new Date().getFullYear()}. All rights reserved.</p>
    </div>

  </div>

</body>
</html>`;

writeFileSync(outputFile, html);

console.log(`\n========================================`);
console.log(`  HTML Report generated!`);
console.log(`  ${outputFile}`);
console.log(`========================================`);
console.log(`  Posts: ${posts.length}`);
console.log(`  Top performers: ${top6.length}`);
console.log(`  Winning patterns: ${patterns.length}`);
console.log(`  Transcripts: ${withTranscripts.length}`);
console.log(`  Screenshots: ${posts.filter(p => p.hasScreenshots).length}`);
console.log(`========================================`);
